### ISSUE TITLE
Installation to objective-c project

### ISSUE THREAD

**Issue by andproff** [thefuntasty/TFTransparentNavigationBar#2]
Hello 
Thanks for your job
I have objective-c project where I need to install TFTransparentNavigationBar
in this case for swift pods is required to add 'use framework!' in Podfile and this broke all objective-c pods
I understood that this is problem of Cocoapods
But my question is:
Can you help me to install TFTransparentNavigationBar by other way?

best regards
Andrei

**Comment by kafejo** [comment]
Hi. You just copy all files from Pod/Classes/ into your project. But I cannot guarantee it will work in objective-c. To be honest I never tried to use it with objective-c therefore there is possibility that you'll have to update the code with some `@objc`. Feel free to create pull request if necessary.
